import './globals.css';

import type { Metadata } from 'next';
import { Comfortaa } from 'next/font/google';

import StoreProvider from './StoreProvider';

const comfortaa = Comfortaa({
  subsets: ['cyrillic'], 
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Менеджер завдань",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
      <html lang="uk">
          <body className={comfortaa.className}>
            <StoreProvider>{children}</StoreProvider>
          </body>    
      </html>
  );
};
